# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

dist: trusty # default "precise" distro doesn't include Java 8 for Elasticsearch 5

env:
  - TOX_ENV=py35-django-18-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py35-django-18-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py34-django-18-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py34-django-18-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py27-django-18-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py27-django-18-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py35-django-19-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py35-django-19-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py34-django-19-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py34-django-19-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py27-django-19-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py27-django-19-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py36-django-110-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py36-django-110-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py35-django-110-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py35-django-110-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py34-django-110-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py34-django-110-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py27-django-110-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py27-django-110-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py36-django-111-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py36-django-111-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py35-django-111-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py35-django-111-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py34-django-111-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py34-django-111-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt
  - TOX_ENV=py27-django-111-es2 ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian
  - TOX_ENV=py27-django-111-es5 ES_APT_URL=https://artifacts.elastic.co/packages/5.x/apt

before_install:
  - pip install codecov
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb $ES_APT_URL stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo service elasticsearch start

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# sleep for elasticsearch
before_script:
  - sleep 10

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV -- --elasticsearch

after_success:
  - codecov -e $TOX_ENV

# publish the package
deploy:
  provider: pypi
  user: travis
  server: https://pypi.liveedu.tv/root/public/
  password:
    secure: "eolwmciRBOmFss6RDxWDoyK97ci2nUybUiQYRnwZIBgxBvWL8rtbI3gX0B+KZT2kf3AMID4x6MHYLDya7gVCFj83OpC/Kf1503X8BDUjsKOvhIcjXQnMm2+Rb1f3w8kWNOnkfSxarpC/BAdfq5NMBDUCpd0gR2jgFu5Hl5iW1z4+H/nBQkCXAMdODR5CtxOhzQYZU3qT5PWlo2cWrIFr8W3C+hRvCDu/Td/D+kHy02H/4YQtz9iwvTDAULdyxvSY3BBooJAG3jmuu7IQm2lHFxatsSnyX2GWlqzHQGvqwLt4C2fT1hglCPLhfyLQtunGhJbg2z7g799stHE+8ks/RfpK7btkYgnpQCqHiN+DcVt2BAGKKEGkQmqFu+Bvp+hVnMWbDGkdA5KNel4knE1K4X0UXzFa6fuN0F9xVCb4AXtjhUn66jz7bDD7D3d0sX6SZD+o61J2zHsc6cebnz726JoeUAahfrl4DlkSYR75Du5EsaWHkrXFf6xnXyhynWLIkWWmZ6OyHBOXdwwDQwvseHN4nX/mreL/plbTCZKx8pYhT1LAXzB25al9rQukqQFmpS18SlX38W22Et4mNGIeRgHNvCQZ7KcS8OpmZcN/+3L2Cddptii1JR3VwTURwWQSLXdhZ8OKoX+lkRbBSr/erb5jtPYjHPOvcXfBVPp16MA="
  distributions: "sdist bdist_wheel"
  on:
    branch: liveedu
